version: "3.8"

services:

  # Eureka Server
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    environment:
      - SERVER_PORT=8761
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=true
      - EUREKA_SERVER_EVICTION_INTERVAL_TIMER_IN_MS=60000

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    environment:
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=api-gateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID=true
      - SPRING_CLOUD_GATEWAY_ROUTES_0_ID=evaluation-service
      - SPRING_CLOUD_GATEWAY_ROUTES_0_URI=lb://EVALUATION-SERVICE
      - SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0=Path=/evaluation/**

  # Evaluation Service
  evaluation-service:
    build: ./evaluation-service
    container_name: evaluation-service
    depends_on:
      - eureka-server
    ports:
      - "8082:8082"
    networks:
      - microservices-network
    environment:
      - SERVER_PORT=8082
      - SPRING_APPLICATION_NAME=evaluation-service
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:evaluationdb
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

networks:
  microservices-network:
    driver: bridge

